spring:
  rabbitmq:
    host: localhost
    port: 5673
    username: ${rabbit-user}
    password: ${rabbit-pass}
  datasource:
    url: jdbc:postgresql://localhost:5432/skttask
    username: ${db-user}
    password: ${db-pass}
    driver-class-name: org.postgresql.Driver
  main:
    web-environment: false


